### ISSUE TITLE
Análise e correção das vulnerabilidades apontadas pelo tfsec

### ISSUE THREAD

**Issue by marcelomansur** [mentoriaiac/iac-modulo-compute-gcp#13]
## Descrevendo o problema

Existem vulerabilidades apontadas pelo tfsec durante a execução do pipeline deste repositório. Identificar quais devem ser tratadas e quais podem ser ignoradas pelo tfsec.

## Reproduzindo o problema

https://github.com/mentoriaiac/iac-modulo-compute-gcp/actions/runs/1370402374

## DoD

 - [ ] Pipeline executado sem erros.

**Comment by gomex** [comment]
Não precisamos mais dessa task, pois o pipeline será centralizado.
